#!/usr/bin/php
<?php

	if (!file_exists("data.csv"))
		echo ("Le fichier n'existe pas");
	else
	{
		echo ( "ok!");
		$ligne = 1; // compteur de ligne
		$file = fopen("data.csv", "r");
		while($tab=fgetcsv($file,';'))
		{
			$champs = count($tab);//nombre de champ dans la ligne en question
			echo("\r\n");

			echo "Les " . $champs . " champs de la ligne " . $ligne . " sont :";
			echo("\r\n");
			$ligne ++;
			//affichage de chaque champ de la ligne en question
			for($i = 0; $i < $champs; $i ++)
			{
				if ($tab[$i] == 0)
					echo $tab[$i] . "\n";
				if ($tab[$i] == 1)
					echo $tab[$i] . "\n";
				if ($tab[$i] == 6)
					echo $tab[$i] . "\n";
			}
		}
	}
?>
