# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba06a9a093fca3b2e88da2c972c0aaae73cea5b5101fbcfbdf742316842def1ed08e157777010396d634ee4e7dd00f8c46cc2f74d02cd92126e072fd2499489

test:
  secret_key_base: a4c2aa47c02a390c460586f89635a9e6955fce78b1baaf57b2839114a8bf4c5b9c411ba81b8618287d75a36cbe0ce5c8326baf985d614ba87d6c7387ac0c5bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
