Rails.application.routes.draw do
	root to: 'moviemon#homepage'
	get 'moviemon/load' => 'moviemon#load'
	get 'moviemon/moviedex' => 'moviemon#moviedex'
	get 'moviemon/next' => 'moviemon#next'
	get 'moviemon/previous' => 'moviemon#previous'
	get 'moviemon/nomovie' => 'moviemon#nomovie'
	get 'play/fight' => 'play#fight'
	get 'play/loose' => 'play#loose'
	get 'play/run' => 'play#run'
	get 'play/success' => 'play#success'
	get 'play/map' => 'play#map'
	get 'play/upsave' => 'play#upsave'
	get 'play/upload' => 'play#upload'
	get 'play/downsave' => 'play#downsave'
	get 'play/download' => 'play#download'
	get 'play/save' => 'play#save'
	get 'play/loadpage' => 'play#loadpage'
	get 'play/load' => 'play#load'
	get 'play/savepage' => 'play#savepage'
	get 'play/finish' => 'play#finish'
	get 'up' => 'play#up'
	get 'left' => 'play#left'
	get 'down' => 'play#down'
	get 'right' => 'play#right'
end
